apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "asoc-members.fullname" . }}-upload-invoices-cron
spec:
  schedule: "20 14 3,10 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}-upload-event-invoices-cron 
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
              {{- range $key, $value := .Values.env }}
                - name: {{ $key | upper | replace "." "_" }}
                  value: {{ quote $value }}
              {{- end }}
              {{- if .Values.secretsName }}
              {{ include "env.secrets" . | indent 16 }}
              {{- end }}
              command:
                - '/bin/bash'
                - '-c' 
                - 'python3 ./manage_and_send_mail.py upload_gdrive_invoices'
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: secrets-files
                  mountPath: "/etc/secrets"
                  readOnly: true
          volumes:
            - name: secrets-files
              secret:
                secretName: {{ .Values.secretsFilesName }}
                items:
                - key: afip_pyar_crt
                  path: afip_pyar.crt
                - key: afip_pyar_key
                  path: afip_pyar.key
                - key: gdrive
                  path: gdrive.json
