kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: redirect-tutorial
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: https://docs.python.org/es/dev/tutorial/
spec:
  tls:
    - hosts:
        - tutorial.python.org.ar
        - tutorial.python.ar
        - tutorial.python.com.ar
        - tutorial.pyar.org.ar
      secretName: tutorial-tls-secret
  rules:
    - host: tutorial.python.org.ar
    - host: tutorial.python.ar
    - host: tutorial.python.com.ar
    - host: tutorial.pyar.org.ar
