apiVersion: v1
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {

      server {
        listen 80 default_server;
        location /nginx-health {
          access_log off;
          return 200 "healthy\n";
        }
      }
      server {  
        listen 80; 
        server_name ar.pycon.org www.pycon.com.ar pycon.com.ar pycon.python.com.ar pyconar.python.org.ar pycon.ar;
        return 301 http://pycon.python.org.ar; 
      } 
      server {
        listen 80;
        server_name web.python.org.ar python.org.ar python.com.ar www.python.com.ar pyar.org.ar www.pyar.org.ar python.ar;
        return 301 https://www.python.org.ar$request_uri;
      }

      server {
        listen 80;
        server_name cdpedia.python.org.ar cdpedia.pyar.org.ar cdpedia.python.com.ar;
        return 301 https://wiki.python.org.ar/Proyectos/cdpedia/;
      }

      server {
        listen 80;
        server_name planeta.python.com.ar planet.python.com.ar planet.python.org.ar;
        return 301 http://planeta.python.org.ar/;
      }
      server {
        listen 80;
        server_name diversidad.python.org.ar;
        return 301 https://ac.python.org.ar/diversidad/index.html;
      }
      server {
        listen 80;
        server_name charlas.python.org.ar listas.python.org.ar;
        return 301 https://pyar.discourse.group/;
      }

    }
 
kind: ConfigMap
metadata:
  name: nginx-config
