apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyarweb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pyarweb.name" . }}
    helm.sh/chart: {{ include "pyarweb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pyarweb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pyarweb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        date/deploy-date: {{ now | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ quote $value }}
          {{- end }}
          {{- if .Values.secretsName }}
          {{ include "env.secrets" . | indent 12 }}
          {{- end }}
          command:
          {{- range .Values.command }}
          - {{ . | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin/login/
              port: http
          readinessProbe:
            httpGet:
              path: /admin/login/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
