{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "join_captcha_bot.serviceAccountName" . }}
  labels:
{{ include "join_captcha_bot.labels" . | indent 4 }}
{{- end -}}
