apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eventol.fullname" . }}-nginx
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        sendfile           on;
        keepalive_timeout  65;

        server {
          listen 0.0.0.0:8001;
          server_name eventos.staging.python.org.ar;
          location / {
            proxy_pass                  http://127.0.0.1:8000;
            proxy_redirect              off;
            proxy_set_header            Host              $host;
            proxy_set_header            X-Real-IP         $remote_addr;
            proxy_set_header            X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header            X-Forwarded-Proto $scheme;
            proxy_connect_timeout       300;
            proxy_send_timeout          300s;
            proxy_read_timeout          300s;
            client_max_body_size        50M;
            send_timeout                300;
         }

          location /media/ {
            alias /usr/src/app/eventol/media/;
            expires max;
          }
          location /static/ {
            alias /usr/src/app/eventol/media/static/;
            expires max;
          }
        }
    }
