apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "eventol.fullname" . }}
  labels:
    app: {{ template "eventol.name" . }}
    chart: {{ template "eventol.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "eventol.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "eventol.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "nginx:alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ quote $value }}
          {{- end }}
          {{- if .Values.secretsName }}
          {{ include "env.secrets" . | indent 12 }}
          {{- end }}
          ports:
            - name: http-nginx
              containerPort: 8001
              protocol: TCP
          volumeMounts:
          - name: mediafiles
            mountPath: {{ .Values.mediafiles.path }}
          - name: nginx-proxy-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - '/bin/ash'
            - '-c' 
            - 'cd eventol&&daphne -b 0.0.0.0 -p 8000 eventol.asgi:channel_layer'
          env: 
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ quote $value }}
          {{- end }}  
          {{- if .Values.secretsName }}
          {{ include "env.secrets" . | indent 12 }}
          {{- end }}  
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            periodSeconds: 30                  
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            periodSeconds: 30                  
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: mediafiles
            mountPath: {{ .Values.mediafiles.path }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: {{ template "eventol.fullname" . }}-nginx
        - name: mediafiles
          azureFile:
            secretName: {{ .Values.mediafiles.azure.secretName }}
            shareName: {{ .Values.mediafiles.azure.shareName }}
            readOnly: false
